apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::962791330624:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-118O1OB565YUA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::962791330624:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-08T12:52:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1570"
  uid: 8e429a09-a8ee-47c8-ab8a-9a2641aa24be
